[workspace]
members = [
    "polars_sheet_reader",
    "strings",
]
resolver = "2"

[workspace.dependencies]
calamine = "0.24.0"
polars = { version = "0.38.1", default-features = false, features = ["lazy", "strings", "regex", "fmt", "dtype-slim"]}
rust_xlsxwriter = { version = "0.63.0", features = ["polars"] }
itertools = "0.12.1"
thiserror = "1.0.57"
