[package]
name = "sheet-utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine.workspace = true
itertools.workspace = true
clap = { version = "4.5.2", features = ["derive"] }
